### PR TITLE
Corrected impl of typeof

### LINKED ISSUE #359: TypeOf failing
TypeOf is defined as both a Node:
https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/ast/node.rs#L421

And a UnaryOp Variant:
https://github.com/jasonwilliams/boa/blob/master/boa/src/syntax/parser/expression/unary.rs#L58-L60

looking at the spec it seems the former is what we should keep and we should remove it from being a unary variant. 

Right now the variant is being used but there's no implementation on the [exec side](https://github.com/jasonwilliams/boa/blob/master/boa/src/exec/mod.rs#L314)

Make some JS, like this to test.
```
const a = String();
typeof a;
```

I'm not sure we will need https://github.com/jasonwilliams/boa/blob/master/boa/src/builtins/value/mod.rs#L631-L651 once Node::TypeOf is being used.

**Spec:**
https://tc39.es/ecma262/#sec-typeof-operator

**Debugging**
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

### PR DESCRIPTION
**Pull request by RestitutorOrbis**
Corrected impl of typeof to follow specification by using relevant
AST node directly instead of using UnaryOp

This Pull Request fixes #359.

It changes the following:
 - Adjusts implementation of TypeOf to use Node::TypeOf instead of Node::UnaryOp

### CODE REVIEW

**Comment by RestitutorOrbis** [comment]
Does this code look alright? I ask because I'm encountering the following bizarre compile error and I'm wondering if there's an alternative route I can pursue:
```bash
error: internal compiler error: src/librustc/ty/steal.rs:34: attempted to read from stolen value

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:875:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0 (4fb7144ed 2020-04-20) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', <::std::macros::panic macros>:5:6

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0 (4fb7144ed 2020-04-20) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `Boa`.
```

**Comment by Razican** [comment]
That is in fact a bug inside the Rust compiler. You should report it, as the error says.

**Comment by jasonwilliams** [comment]
> Hi! thanks for the contribution. After some discussion in #359, it seems that it's best if we implement this as a unary expression and remove the `Node`, then move the `exec` part to the unary expression execution.
> 
> We should also add tests to this.

Yeah sorry about that its may fault i was under the impression it was a Node expression and not a unary one.

File: boa/src/exec/mod.rs [hunk 1]
```diff
@@ -420,10 +420,24 @@ impl Executor for Interpreter {
...
+                        ValueData::String(_) => "string",
+                        ValueData::Object(ref o) => {
+                            if o.deref().borrow().is_callable() {
+                                "function"
+                            } else {
+                                "object"
+                            }
+                        }
+                    }),
                     _ => unimplemented!(),
```
Comment (Razican) [inline boa/src/exec/mod.rs:441]: It seems that we already implemented all variants, so this is unreachable :D
```suggestion
```

File: boa/src/exec/tests.rs [hunk 2]
```diff
@@ -385,6 +385,62 @@ fn unary_pre() {
...
+    let undefined_type_result = String::from("undefined");
+    let boolean_type_result = String::from("boolean");
+    let object_type_result = String::from("object");
+    let function_type_result = String::from("function");
+    let symbol_type_result = String::from("symbol");
+    let typeof_string = r#"
+        const a = String();
+        typeof a;
+    "#;
+    assert_eq!(exec(typeof_string), string_type_result);
```
Comment (Razican) [inline boa/src/exec/tests.rs:401]: I think this is more clear if we do it like this:
```suggestion
    assert_eq!(&exec(typeof_string), "string");

```
Also adding a new line after each assert, to separate them.

File: boa/src/syntax/ast/node.rs [hunk 3]
```diff
@@ -469,22 +469,7 @@ pub enum Node {
...
-    ///  - [ECMAScript reference][spec]
-    ///  - [MDN documentation][mdn]
-    ///
-    /// [spec]: https://tc39.es/ecma262/#sec-typeof-operator
-    /// [mdn]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof
-    TypeOf(Box<Node>),
-
-    /// The `try...catch` statement marks a block of statements to try and specifies a response
-    /// should an exception be thrown.
+    /// The `try...catch` statement marks a block of statements to try and specifies a response should an exception be thrown.
```
Comment (Razican) [inline boa/src/syntax/ast/node.rs:472]: Hmmm why was this moved to one line? Rust recommends having 100 characters per line, was it too short?

Comment (RestitutorOrbis) [reply boa/src/syntax/ast/node.rs:472]: My IDE must have done this, I'll revert it

File: boa/src/exec/mod.rs [hunk 4]
```diff
@@ -420,11 +420,24 @@ impl Executor for Interpreter {
...
+                        ValueData::Rational(_) | ValueData::Integer(_) => "number",
+                        ValueData::String(_) => "string",
+                        ValueData::Object(ref o) => {
+                            if o.deref().borrow().is_callable() {
+                                "function"
+                            } else {
+                                "object"
+                            }
+                        }
+                    }),
```
Comment (HalidOdat) [inline boa/src/exec/mod.rs:440]: Why do we do this here when we can just call `value.get_type()` which returns a `&'static str` it seems like were duping code.

Comment (jasonwilliams) [reply boa/src/exec/mod.rs:440]: I think i mentioned in the original issue that we don't need both https://github.com/jasonwilliams/boa/issues/359#issue-610887558

Comment (jasonwilliams) [reply boa/src/exec/mod.rs:440]: as @HalidOdat said maybe we can just call get_type() from here

File: boa/src/builtins/value/operations.rs [hunk 5]
```diff
@@ -18,6 +18,13 @@ impl Value {
             return number::equals(f64::from(self), f64::from(other));
         }
 
+        //Null has to be handled specially because "typeof null" returns object and if we managed
+        //this without a special case we would compare self and other as if they were actually
+        //objects which unfortunately fails
+        if self.is_null() {
+            return true;
+        }
+
```
Comment (Razican) [inline boa/src/builtins/value/operations.rs:27]: Can we add a test for this, and a link to the spec?

Comment (RestitutorOrbis) [reply boa/src/builtins/value/operations.rs:27]: Isn't boa/src/builtins/value/tests.rs:58 already a test for this?

**Comment by RestitutorOrbis** [comment]
I'm having difficulty replicating the errors in CI on my local development environments (Windows and Mac OSX). I'm not entirely sure where to proceed from here so I would love to have some suggestions!

**Comment by jasonwilliams** [comment]
> I'm having difficulty replicating the errors in CI on my local development environments (Windows and Mac OSX). I'm not entirely sure where to proceed from here so I would love to have some suggestions!

Looks like you've found a regression introduced by my ["implement this"](https://github.com/jasonwilliams/boa/pull/320) change

I will look at this.

**Comment by RestitutorOrbis** [comment]
> > I'm having difficulty replicating the errors in CI on my local development environments (Windows and Mac OSX). I'm not entirely sure where to proceed from here so I would love to have some suggestions!
> 
> Looks like you've found a regression introduced by my ["implement this"](https://github.com/jasonwilliams/boa/pull/320) change
> 
> I will look at this.

Thanks!

**Comment by jasonwilliams** [comment]
Lets see if https://github.com/jasonwilliams/boa/pull/407 passes and ill merge that, String wasn't defaulting to empty when being called as `const a = String()`

The fact that you made a test for this is great as we may not have captured that before

**Comment by jasonwilliams** [comment]
https://github.com/jasonwilliams/boa/pull/407 merged

File: boa/src/builtins/value/operations.rs (hunk 5 above)
Comment (Razican) [reply boa/src/builtins/value/operations.rs]: Yes! Perfect, rhanks! :)
