### PR TITLE
Constants must have a value on declaration

### LINKED ISSUE #46: empty `const` declaration should fail
## Specification:
https://tc39.es/ecma262/#sec-let-and-const-declarations-static-semantics-early-errors
_It is a Syntax Error if Initializer is not present and IsConstantDeclaration of the LexicalDeclaration containing this LexicalBinding is true._

### Expected
```js
const a = 5, b, c = 6;"
```
Should fail, binding `b` is not initialised

### Related to:
https://github.com/jasonwilliams/boa/pull/42/files#diff-9f9158af1c9e00d4a93319c5918d9b97R924

### Parser const decl location
https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/parser.rs#L79-L133 

### Contributing
https://github.com/jasonwilliams/boa/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Razican**
This fixes #46. I just modified constant declarations so that it's impossible to have a constant without a value. I also uncommented the test that was failing.

### CODE REVIEW

File: src/lib/syntax/ast/expr.rs [hunk 1]
```diff
@@ -200,6 +198,13 @@ impl Display for ExprDef {
                 }
                 f.write_str("")
             }
+            ExprDef::ConstDeclExpr(ref vars) => {
+                f.write_str("var ")?;
```
Comment (jasonwilliams) [inline src/lib/syntax/ast/expr.rs]: does this need to be `f.write_str("const ")?;` ?

Comment (Razican) [reply src/lib/syntax/ast/expr.rs]: Ups, yes, I copied it from above.

**Comment by Razican** [comment]
I think this should be done now :)
